---
# tasks file for mariadb-install
- include_tasks: setup-fedora29.yml
  when: 
   -ansible_os_family == 'Fedora'
   -ansible_distribution_major_version == "29"

- include_tasks: setup-fedora24.yml
  when: 
    -ansible_os_family == 'Fedora'
    -ansible_distribution_major_version == "24"
